### ISSUE TITLE
Heal Predictions are not working in WotLK Classic

### ISSUE THREAD

**Issue by KinjeDL** [Resike/Z-Perl#27]
TBC and older ranks of spells still work.  it's just the new WotLK ranks that don't.

**Comment by Fieora** [comment]
Seems like the Heal comm library is to blame for this, it is still not updated with wrath spell ranks.

**Comment by KinjeDL** [comment]
> Seems like the Heal comm library is to blame for this, it is still not updated with wrath spell ranks.

That's what I don't get, it looks like LibHealComm-4.0.lua included with ZPerl is updated.  It has the latest ranks of all my druid heals, at least, including the ones that aren't working.

**Comment by Fieora** [comment]
should be working now, turns out back in TBC it switched to the back-ported default api, (which only shows direct casted heals).
I think blizzard has fixed that now, I did create a PR to get hots back(with configs)

Note, while z-perl does support absorbs, for classic neither the api nor healcomm report on them, so they don't work.
