### ISSUE TITLE
10.1 errors

### ISSUE THREAD

**Issue by derekwengstrom** [Resike/Z-Perl#61]
Getting the following error after logging in:

Message: Interface/AddOns/ZPerl/ZPerl.lua:2192: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: XPerl_TargetTarget:SetPoint.
Time: Wed May  3 22:08:31 2023
Count: 1
Stack: Interface/AddOns/ZPerl/ZPerl.lua:2192: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: XPerl_TargetTarget:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface/AddOns/ZPerl/ZPerl.lua"]:2192: in function `XPerl_RestoreAllPositions'
[string "@Interface/AddOns/ZPerl/ZPerl_Globals.lua"]:574: in function `XPerl_LoadFrameLayout'
[string "@Interface/AddOns/ZPerl/ZPerl_Globals.lua"]:624: in function <Interface/AddOns/ZPerl/ZPerl_Globals.lua:591>

Locals: (*temporary) = XPerl_TargetTarget {
 0 = <userdata>
 highlight = XPerl_TargetTargethighlight {
 }
 nameFrame = XPerl_TargetTargetnameFrame {
 }
 lastUpdate = 0
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 buffFrame = XPerl_TargetTargetbuffFrame {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 targetname = ""
 buffSetup = <table> {
 }
 statsFrame = XPerl_TargetTargetstatsFrame {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 partyid = "targettarget"
 conf = <table> {
 }
 guid = 0
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 debuffFrame = XPerl_TargetTargetdebuffFrame {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 parentid = "target"
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 levelFrame = XPerl_TargetTargetlevelFrame {
 }
}
(*temporary) = "TOPLEFT"
(*temporary) = UIParent {
 0 = <userdata>
 Tabs = <table> {
 }
 ContainerFrames = <table> {
 }
 firstTimeLoaded = 1
 variablesLoaded = true
}
(*temporary) = "BOTTOMLEFT"
(*temporary) = 581.861023
(*temporary) = 1333.894897

**Comment by Ssesmar** [comment]
got the same error. no combopoints on playerframe

1x ZPerl/ZPerl.lua:2192: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: XPerl_Focus:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@ZPerl/ZPerl.lua"]:2192: in function `XPerl_RestoreAllPositions'
[string "@ZPerl/ZPerl_Globals.lua"]:574: in function `XPerl_LoadFrameLayout'
[string "@ZPerl/ZPerl_Globals.lua"]:624: in function <ZPerl/ZPerl_Globals.lua:591>

Locals:
(*temporary) = XPerl_Focus {
 bossFrame = XPerl_FocusbossFrame {
 }
 perlBuffs = 0
 portraitFrame = XPerl_FocusportraitFrame {
 }
 nameFrame = XPerl_FocusnameFrame {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 partyid = "focus"
 hitIndicator = XPerl_FocushitIndicator {
 }
 combatMask = 131072
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 eliteFrame = XPerl_FocuseliteFrame {
 }
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 highlight = XPerl_Focushighlight {
 }
 cpFrame = XPerl_FocuscpFrame {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 creatureTypeFrame = XPerl_FocuscreatureTypeFrame {
 }
 0 = <userdata>
 statsFrame = XPerl_FocusstatsFrame {
 }
 typeFramePlayer = XPerl_FocustypeFramePlayer {
 }
 FlashFrames = <table> {
 }
 conf = <table> {
 }
 time = 0
 buffSetup = <table> {
 }
 perlDebuffs = 0
 feedbackFontHeight = 30
 feedbackText = XPerl_FocushitIndicatortext {
 }
 buffFrame = XPerl_FocusbuffFrame {
 }
 debuffFrame = XPerl_FocusdebuffFrame {
 }
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 levelFrame = XPerl_FocuslevelFrame {
 }
}
(*temporary) = "TOPLEFT"
(*temporary) = UIParent {
 0 = <userdata>
 Tabs = <table> {
 }
 ContainerFrames = <table> {
 }
 firstTimeLoaded = 1
 variablesLoaded = true
}
(*temporary) = "BOTTOMLEFT"
(*temporary) = 340.473206
(*temporary) = 876.102234
