### ISSUE TITLE
Spammed with "you aren't in a party" when healing people in RDF in WOTLK Classic

### ISSUE THREAD

**Issue by Ehr1337** [Resike/Z-Perl#90]
Any Fix for this it's non stop when playing a resto druid

**Comment by Tjc222** [comment]
Same thing is happening with me. I would love to continue using Zperl but, It's just non stop spamming in dungeons.

**Comment by warcraftclassicgamer** [comment]
This has been happening ever since P4 released. Hang it up boys. The owner has stopped fixing the errors. Not only are we spammed with the annoying message but the "fix" _that someone else came up with mind you_, is to delete some lines but not only are we still being spammed, but the mob type always says "none". This was reported several weeks ago. Seeing a whole lot of complaints and nothing but radio silence.

https://github.com/Resike/Z-Perl/issues/87#issue-1952553147

**Comment by Resike** [comment]
Fixed with next release.
